# local server setting
server:
   host: localhost
   port: 8090


# output service of the registry: it can be set either to "mongo" or "fabric"
out-service:
   name: mongo
   ip: localhost
   port: 27017
   dbname: sunfish-registry
   dbcollection: keyValueStore
   hl_invoke_type: invoke        #it can be "invoke" or "put"; invoke is general purpose, "put" is just for keyValueStore chaincode
   hl_user: ubuntu
   hl_password: ubuntu
   hl_ip: 192.168.1.107
   hl_port: 22
   hl_channel: mychannel
   hl_chaincode: keyValueStore
   hl_dockerid: 1db78d826131
   hl_script_path: /opt/gopath/src/github.com/hyperledger/fabric/examples/e2e_cli/scripts/
   hl_endorser_peer: 0

hyperledger-service:
   host: localhost
   port: 4000
   path: 
     install: /chaincodes
     init: /channels/mychannel/chaincodes
     invoke: /channels/mychannel/chaincodes
