# output service of the registry: it can be set either to "mongo" or "fabric"
out-service:
   name: fabric
   ip: localhost
   port: 27017
   dbname: sunfish-registry
   dbcollection: keyValueStore
   hl_user: ubuntu
   hl_password: ubuntu
   hl_ip: 192.168.1.107
   hl_port: 22
   hl_channel: mychannel
   hl_chaincode: mycc2
   hl_dockerid: 2425a915d7c4
   hl_script_path: /opt/gopath/src/github.com/hyperledger/fabric/examples/e2e_cli/scripts/
